### ISSUE TITLE
how to use `unbind` ?

### ISSUE THREAD

**Issue by codering** [KyleAMathews/element-resize-event#12]
use in es6

```js
import elementResizeEvent, {unbind} from 'element-resize-event'
```

but the `unbind` is undefined

**Comment by plgregoire** [comment]
I'm also interested in knowing how ?

**Comment by trevordmiller** [comment]
Pull request submitted to add documentation for `unbind`: https://github.com/KyleAMathews/element-resize-event/pull/20
