### ISSUE TITLE
TypeError: Cannot read property 'resize' of null"

### ISSUE THREAD

**Issue by hustcc** [KyleAMathews/element-resize-event#16]
[echarts-for-react](https://github.com/hustcc/echarts-for-react) has depends on `element-resize-event`.

Users report bug of **TypeError: Cannot read property 'resize' of null"**(https://github.com/hustcc/echarts-for-react/issues/43), maybe bug of element-resize-event.

**Comment by KyleAMathews** [comment]
If it is happy to take a PR to fix things.

**Comment by hustcc** [comment]
Sorry for that, Maybe I do not know how to fix it. :cry:
