### ISSUE TITLE
Unbind event?

### ISSUE THREAD

**Issue by jasonkuhrt** [KyleAMathews/element-resize-event#2]
It appears there is no way to remove event handlers. Is this correct?

**Comment by KyleAMathews** [comment]
Not yet. Note we'd also need to clean up the extra elements that are added. PR welcome or I'll get to this eventually.

**Comment by jasonkuhrt** [comment]
I will try to cook something up...

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by ggoodman** [comment]
Has anyone made any un-published progress on this?

**Comment by agarcher** [comment]
There is another library that gives element level resize notifications and has unbind support. See https://github.com/marcj/css-element-queries. The main focus of the plugin is much higher level (to provide css element queries, not just resize detection), but it does expose a small module that does the resize tracking only.

See https://github.com/marcj/css-element-queries/blob/master/src/ResizeSensor.js and the "ResizeSensor Demo" section at http://marcj.github.io/css-element-queries/

**Comment by countravioli** [comment]
Can this issue be closed?

**Comment by KyleAMathews** [comment]
Yup!

**Comment by trevordmiller** [comment]
Pull request submitted to add documentation for `unbind`: https://github.com/KyleAMathews/element-resize-event/pull/20
