### ISSUE TITLE
It appears like this repo is dead ...

### ISSUE THREAD

**Issue by drcmda** [KyleAMathews/element-resize-event#26]
But there's a critical bug that doesn't allow it to run in a modern build setup. So i forked it and added all the PR's waiting for approval. 

https://github.com/drcmda/dom-resize

**Comment by KyleAMathews** [comment]
Not dead (whatever that means). I'd be happy to add you as a maintainer
here. Been busy on other open source projects

**Comment by drcmda** [comment]
My apologies, i had assumed it was an abandoned repo given that there was no response. I really wish i could help out, but i'm in a tight schedule due to the project i'm sitting on. The package was crashing our build so i thought i'll set it back to an older version, make a a PR and wait. It's been several months, i eventually decided to fork but would be glad to just continue using element-resize-event if it worked.

**Comment by naivefun** [comment]
How about using polling size to implement this feature? like every 20ms?

**Comment by eaglus** [comment]
Feel free to make PRs, now repository is maintained. New version with some bugfixes issued
