### ISSUE TITLE
Cannot read property 'requestAnimationFrame' of undefined

### ISSUE THREAD

**Issue by hustcc** [KyleAMathews/element-resize-event#29]
Issue here: https://github.com/hustcc/echarts-for-react/issues/148

because of babel 6 add `use strict` by default. add plugin `transform-remove-strict-mode` will be ok.

Also rewrite it with es6 [here](https://github.com/hustcc/size-sensor).

**Comment by lkiarest** [comment]
I locked the package version to element-resize-event@2.0.7 and resolved.
