### ISSUE TITLE
resize event doesn't get triggered on Chrome

### ISSUE THREAD

**Issue by junaidahmed501** [KyleAMathews/element-resize-event#35]
I'm using this package in Angular 7 in OnInit method which seems to be working ok in Firefox but not in Chrome Version 80.0.3987.106 (Official Build) (64-bit). Technically it shouldn't be working in Firefox as I don't resize the element on page load.

**Comment by jpgaghan** [comment]
Jun if you are using react it's because this is no longer a dependency of react-sticky-pages. Would update react-sticky-pages and get rid of this import from your project if you use it.
import 'react-sticky-table/dist/react-sticky-table.css'

**Comment by junaidahmed501** [comment]
> Jun if you are using react it's because this is no longer a dependency of react-sticky-pages. Would update react-sticky-pages and get rid of this import from your project if you use it.
> import 'react-sticky-table/dist/react-sticky-table.css'
